name: Verify

on:
  # Trigger the workflow on push or pull request on master branch
  pull_request:
    branches:
    - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build & Test
      run: make podman podman-rootless podman-remote test
