name: Verify

on:
  # Trigger the workflow on push or pull request on master branch
  pull_request:
    branches:
    - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Build & test linux/amd64 image
      run: make create-builder images test

    - name: Build cross-platform binaries and images (quick binary test only)
      run: make multiarch

    - name: Build cross-platform image
      run: make images PLATFORM="linux/amd64,linux/arm64/v8

